CREATE OR REPLACE VIEW view_bi_loja_devolucao AS 

SELECT 
    PCDATAS.DATA,
    NVL(FILIAL.COD_FILIAL,0)COD_FILIAL,
    NVL(DEVOLUCAO.VLR_DEVOLUCAO,0) VLR_DEVOLUCAO,
    NVL(DEVOLUCAO.VLR_DEV_SEM_TV8,0) VLR_DEV_SEM_TV8,
    NVL(DEVOLUCAO.VLR_DEV_AVULSA,0) VLR_DEV_AVULSA
FROM PCDATAS 
    LEFT JOIN (
                    SELECT 
                        PCFILIAL.CODIGO COD_FILIAL,
                        PCFILIAL.DTREGISTRO REGISTRO 
                    FROM 
                        PCFILIAL 
                    WHERE PCFILIAL.CODIGO NOT IN (7)
                )FILIAL 
            ON PCDATAS.DATA > FILIAL.REGISTRO                    

    LEFT JOIN (     SELECT
                        PCESTCOM.DTESTORNO DATA,
                        PCNFENT.CODFILIAL COD_FILIAL,
                        COUNT(DISTINCT PCNFENT.CODFORNEC) QTD_CLIENTE,
                        SUM(CASE WHEN PCESTCOM.NUMTRANSVENDA IS NOT NULL THEN PCESTCOM.VLDEVOLUCAO ELSE 0 END) VLR_DEVOLUCAO,
                        SUM(DECODE((SELECT S.CONDVENDA FROM PCNFSAID S WHERE S.NUMTRANSVENDA = PCESTCOM.NUMTRANSVENDA ),8,0,
                                           (CASE WHEN PCESTCOM.NUMTRANSVENDA IS NOT NULL THEN  NVL(PCESTCOM.VLDEVOLUCAO,0) ELSE 0 END) )) VLR_DEV_SEM_TV8,
                        SUM(CASE WHEN PCESTCOM.NUMTRANSVENDA IS NOT NULL THEN 0 ELSE PCESTCOM.VLDEVOLUCAO END) VLR_DEV_AVULSA  
                    FROM 
                        PCESTCOM,PCNFENT
                    WHERE
                        PCESTCOM.NUMTRANSENT = PCNFENT.NUMTRANSENT
                    
                    GROUP BY 
                        PCESTCOM.DTESTORNO,
                        PCNFENT.CODFILIAL) DEVOLUCAO 
                ON PCDATAS.DATA = DEVOLUCAO.DATA
                AND FILIAL.COD_FILIAL = DEVOLUCAO.COD_FILIAL
    
WHERE PCDATAS.DATA BETWEEN ADD_MONTHS( TRUNC(SYSDATE,'YY'),-12) AND ADD_MONTHS( LAST_DAY(TRUNC(SYSDATE)),0)
ORDER BY DATA, COD_FILIAL
 WITH READ ONLY    

