SELECT   
  MATRICULA,    
  PCEMPR.NOME NOME,
  (CASE WHEN (INSTR(PCEMPR.NOME, ' ') = 0) THEN PCEMPR.NOME ELSE SUBSTR(PCEMPR.NOME,0,INSTR(PCEMPR.NOME, ' ')-1)||' '||SUBSTR(PCEMPR.NOME,INSTR(PCEMPR.NOME, ' ',-1)+1) END )NOME_RED,    
    DECODE(SITUACAO,'A','ATIVO','INATIVO')SITUACAO
FROM 
    PCEMPR
WHERE 
    CODSETOR =2 ORDER BY MATRICULA
